version: "3.7"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - /Users/seokmin/works/postgres-data:/var/lib/postgresql/data
