name: build-dockerize

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  REPOSITORY: ${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}
  REGISTRY: 802797423270.dkr.ecr.ap-northeast-2.amazonaws.com
  DATABASE_URL: ${{ secrets.DATABASE_URL}}
  SECRET: ${{ secrets.SECRET}}
  KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID}}
  KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET}}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL}}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_REGION: ${{ secrets.AWS_REGION}}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME}}

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      # see: https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ECR_PUSH_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_PUSH_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
#  Deploy:
#    needs: Build
#    uses: alookso/argocd-resources/.github/workflows/update-kustomize.yaml@main
#    with:
#      repository: ${{ github.repository }}
#      environment: staging
#      image-tag: ${{ github.sha }}
#      branch: main
#    secrets:
#      github-access-token: ${{ secrets.ACCESS_TOKEN }}
