# name: deploy-argocd

# on:
#   workflow_dispatch:
#     inputs:
#       imageTag:
#         description: 'input deployment image tag'
#         required: true
# jobs:
#   deployment:
#     uses: alookso/argocd-resources/.github/workflows/update-kustomize.yaml@main
#     with:
#       repository: ${{ github.repository }}
#       environment: production
#       image-tag: ${{ inputs.imageTag }}
#       branch: main
#     secrets:
#       github-access-token: ${{ secrets.ACCESS_TOKEN }}
